channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.0.1
- pip:
  - mlflow==2.20.2
  - astunparse==1.6.3
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.3
  - torch==2.6.0
  - tqdm==4.67.1
name: mlflow-env
