#version: '3.7'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      - BACKEND_STORE_URI=postgresql://mlflow_user:mlflow_pass@db/mlflow_db
      - ARTIFACT_ROOT=/mlflow/artifacts
    ports:
      - "5001:5001"
    depends_on:
      - db
    command: >
      mlflow server --backend-store-uri postgresql://aiml_orchestrators_user:aiml_orchestrators_password@db/aiml_orchestrators_asssignment
      --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000
    volumes:
      - ./mlruns:/mlflow/artifacts
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: aiml_orchestrators_asssignment
      POSTGRES_USER: aiml_orchestrators_user
      POSTGRES_PASSWORD: aiml_orchestrators_password
    ports:
      - "5432:5432"
