version: '3.8'  #You can remove this line if using Docker Compose v2

services:
  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"  # FastAPI
      - "8888:8888"  # Jupyter Notebook
      - "5000:5000"  # MLflow UI
    restart: always

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8080:8080"  # Web UI
    depends_on:
      - fastapi
    restart: always
